using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;

namespace PLC
{
    public class LLVMGenerator : IGenerator
    {
        public ParsedProgram Program { get; set; }
        int _labelCounter = 0;
        int _tempCounter = 0;
        readonly List<string> _stringLiterals = new();
        HashSet<string> _globalVars = new();
        Dictionary<string, string> _localVarAllocas = new();

        public LLVMGenerator(ParsedProgram program)
        {
            Program = program;
        }

        public int Compile(string filename)
        {
            var lines = Generate();
            using (var writer = new StreamWriter(filename))
            {
                foreach (string line in lines)
                    writer.WriteLine(line);
            }
            return 0;
        }

        public IEnumerable<string> Generate()
        {
            _labelCounter = 0;
            _tempCounter = 0;
            _stringLiterals.Clear();
            _globalVars = new HashSet<string>();
            _localVarAllocas = new Dictionary<string, string>();

            CollectStringLiterals(Program.Block.Statement);

            yield return "; LLVM IR generated by plc";
            yield return "target triple = \"x86_64-pc-linux-gnu\"";
            yield return "";

            yield return "@fmt_d = constant [4 x i8] c\"%d\\0A\\00\"";
            yield return "@fmt_scan = constant [3 x i8] c\"%d\\00\"";
            yield return "";

            for (int i = 0; i < _stringLiterals.Count; i++)
            {
                string escaped = EscapeString(_stringLiterals[i]);
                yield return "@str" + i + " = constant [" + (escaped.Length + 1) + " x i8] c\"" + escaped + "\\00\"";
            }
            if (_stringLiterals.Count > 0)
                yield return "";

            var constants = Program.Block.Constants;
            if (constants.Count > 0)
            {
                foreach (var c in constants)
                    yield return "@" + c.Name + " = constant i32 " + c.Value;
                yield return "";
            }

            foreach (var v in Program.Block.Variables)
            {
                _globalVars.Add(v.Name);
                yield return "@" + v.Name + " = global i32 0";
            }

            if (Program.Block.Variables.Count > 0)
                yield return "";

            yield return "declare i32 @printf(i8*, ...)";
            yield return "declare i32 @scanf(i8*, ...)";
            yield return "declare i32 @puts(i8*)";
            yield return "declare i32 @time(i32*)";
            yield return "declare i32 @srand(i32)";
            yield return "declare i32 @rand()";
            yield return "";

            foreach (var proc in Program.Block.Procedures)
            {
                var procLocals = new HashSet<string>(proc.Block.Variables.Select(v => v.Name));
                _localVarAllocas = new Dictionary<string, string>();
                yield return "define i32 @proc_" + proc.Name + "() {";
                var procLines = new List<string>();
                foreach (var v in proc.Block.Variables)
                {
                    string ptr = NewTemp();
                    _localVarAllocas[v.Name] = ptr;
                    procLines.Add(ptr + " = alloca i32");
                    procLines.Add("store i32 0, i32* " + ptr);
                }
                GenerateStatement(proc.Block.Statement, procLines, procLocals);
                foreach (string s in procLines)
                    yield return "  " + s;
                yield return "  ret i32 0";
                yield return "}";
                yield return "";
            }

            yield return "define i32 @main() {";
            var mainLines = new List<string>();
            if (Program.UsesRand)
            {
                string t = NewTemp();
                mainLines.Add(t + " = call i32 @time(i32* null)");
                mainLines.Add("call i32 @srand(i32 " + t + ")");
            }
            GenerateStatement(Program.Block.Statement, mainLines, new HashSet<string>());
            foreach (string s in mainLines)
                yield return "  " + s;
            yield return "  ret i32 0";
            yield return "}";
        }

        void CollectStringLiterals(Statement stmt)
        {
            if (stmt is WriteStatement ws)
            {
                if (ws.Message != String.Empty && !_stringLiterals.Contains(ws.Message))
                    _stringLiterals.Add(ws.Message);
            }
            else if (stmt is ReadStatement rs)
            {
                if (rs.Message != String.Empty && !_stringLiterals.Contains(rs.Message))
                    _stringLiterals.Add(rs.Message);
            }
            else if (stmt is CompoundStatement cs)
            {
                foreach (var s in cs.Statements)
                    CollectStringLiterals(s);
            }
            else if (stmt is IfStatement ifs)
            {
                CollectStringLiterals(ifs.Statement);
            }
            else if (stmt is WhileStatement ws2)
            {
                CollectStringLiterals(ws2.Statement);
            }
            else if (stmt is DoWhileStatement dws)
            {
                CollectStringLiterals(dws.Statement);
            }
        }

        string VarRef(string name, HashSet<string> locals)
        {
            if (locals.Contains(name))
                return _localVarAllocas[name];
            return "@" + name;
        }

        string NewLabel()
        {
            return "L" + (_labelCounter++);
        }

        string NewTemp()
        {
            return "%t" + (_tempCounter++);
        }

        int GetStringLiteralIndex(string message)
        {
            int index = _stringLiterals.IndexOf(message);
            if (index == -1)
            {
                index = _stringLiterals.Count;
                _stringLiterals.Add(message);
            }
            return index;
        }

        void GenerateStatement(Statement statement, List<string> lines, HashSet<string> locals)
        {
            if (statement is WriteStatement ws)
            {
                if (ws.Message == String.Empty)
                {
                    string valReg = GenerateExpression(ws.Expression, lines, locals);
                    string fmtPtr = NewTemp();
                    lines.Add(fmtPtr + " = getelementptr [4 x i8], [4 x i8]* @fmt_d, i32 0, i32 0");
                    lines.Add("call i32 (i8*, ...) @printf(i8* " + fmtPtr + ", i32 " + valReg + ")");
                }
                else
                {
                    int idx = GetStringLiteralIndex(ws.Message);
                    int len = ws.Message.Length + 1;
                    string ptr = NewTemp();
                    lines.Add(ptr + " = getelementptr [" + len + " x i8], [" + len + " x i8]* @str" + idx + ", i32 0, i32 0");
                    lines.Add("call i32 @puts(i8* " + ptr + ")");
                }
            }
            else if (statement is ReadStatement rs)
            {
                if (rs.Message != String.Empty)
                {
                    int idx = GetStringLiteralIndex(rs.Message);
                    int len = rs.Message.Length + 1;
                    string msgPtr = NewTemp();
                    lines.Add(msgPtr + " = getelementptr [" + len + " x i8], [" + len + " x i8]* @str" + idx + ", i32 0, i32 0");
                    lines.Add("call i32 (i8*, ...) @printf(i8* " + msgPtr + ")");
                }
                string fmtPtr = NewTemp();
                lines.Add(fmtPtr + " = getelementptr [3 x i8], [3 x i8]* @fmt_scan, i32 0, i32 0");
                lines.Add("call i32 (i8*, ...) @scanf(i8* " + fmtPtr + ", i32* " + VarRef(rs.IdentityName, locals) + ")");
            }
            else if (statement is AssignmentStatement ass)
            {
                string valReg = GenerateExpression(ass.Expression, lines, locals);
                lines.Add("store i32 " + valReg + ", i32* " + VarRef(ass.IdentityName, locals));
            }
            else if (statement is CallStatement cs)
            {
                lines.Add("call i32 @proc_" + cs.ProcedureName + "()");
            }
            else if (statement is CompoundStatement comp)
            {
                foreach (var s in comp.Statements)
                {
                    if (!s.SkipGeneration)
                        GenerateStatement(s, lines, locals);
                }
            }
            else if (statement is IfStatement ifs)
            {
                string condReg = GenerateCondition(ifs.Condition, lines, locals);
                string bodyLabel = NewLabel();
                string endLabel = NewLabel();
                lines.Add("br i1 " + condReg + ", label %" + bodyLabel + ", label %" + endLabel);
                lines.Add("");
                lines.Add(bodyLabel + ":");
                GenerateStatement(ifs.Statement, lines, locals);
                lines.Add("br label %" + endLabel);
                lines.Add("");
                lines.Add(endLabel + ":");
            }
            else if (statement is WhileStatement wls)
            {
                if (wls.Condition is TrueCondition)
                {
                    string startLabel = NewLabel();
                    lines.Add("br label %" + startLabel);
                    lines.Add("");
                    lines.Add(startLabel + ":");
                    GenerateStatement(wls.Statement, lines, locals);
                    lines.Add("br label %" + startLabel);
                }
                else
                {
                    string condLabel = NewLabel();
                    string bodyLabel = NewLabel();
                    string endLabel = NewLabel();
                    lines.Add("br label %" + condLabel);
                    lines.Add("");
                    lines.Add(condLabel + ":");
                    string condReg = GenerateCondition(wls.Condition, lines, locals);
                    lines.Add("br i1 " + condReg + ", label %" + bodyLabel + ", label %" + endLabel);
                    lines.Add("");
                    lines.Add(bodyLabel + ":");
                    GenerateStatement(wls.Statement, lines, locals);
                    lines.Add("br label %" + condLabel);
                    lines.Add("");
                    lines.Add(endLabel + ":");
                }
            }
            else if (statement is DoWhileStatement dws)
            {
                if (dws.Condition is TrueCondition)
                {
                    string startLabel = NewLabel();
                    lines.Add("br label %" + startLabel);
                    lines.Add("");
                    lines.Add(startLabel + ":");
                    GenerateStatement(dws.Statement, lines, locals);
                    lines.Add("br label %" + startLabel);
                }
                else
                {
                    string startLabel = NewLabel();
                    string endLabel = NewLabel();
                    lines.Add("br label %" + startLabel);
                    lines.Add("");
                    lines.Add(startLabel + ":");
                    GenerateStatement(dws.Statement, lines, locals);
                    string condReg = GenerateCondition(dws.Condition, lines, locals);
                    lines.Add("br i1 " + condReg + ", label %" + startLabel + ", label %" + endLabel);
                    lines.Add("");
                    lines.Add(endLabel + ":");
                }
            }
        }

        string GenerateExpression(Expression expr, List<string> lines, HashSet<string> locals)
        {
            if (expr is RandExpression rand)
            {
                return GenerateRandExpression(rand, lines, locals);
            }

            var nodes = expr.ExpressionNodes;
            if (nodes.Count == 0)
            {
                string z = NewTemp();
                lines.Add(z + " = add i32 0, 0");
                return z;
            }

            string result = GenerateTerm(nodes[0].Term, lines, locals);
            if (!nodes[0].IsPositive)
            {
                string neg = NewTemp();
                lines.Add(neg + " = sub i32 0, " + result);
                result = neg;
            }

            for (int i = 1; i < nodes.Count; i++)
            {
                string termReg = GenerateTerm(nodes[i].Term, lines, locals);
                string newResult = NewTemp();
                if (nodes[i].IsPositive)
                    lines.Add(newResult + " = add i32 " + result + ", " + termReg);
                else
                    lines.Add(newResult + " = sub i32 " + result + ", " + termReg);
                result = newResult;
            }

            return result;
        }

        string GenerateRandExpression(RandExpression r, List<string> lines, HashSet<string> locals)
        {
            string lowExpr = GenerateExpression(r.LowExpression, lines, locals);
            string highExpr = GenerateExpression(r.HighExpression, lines, locals);
            string randVal = NewTemp();
            string diff = NewTemp();
            string diff1 = NewTemp();
            string modVal = NewTemp();
            string result = NewTemp();
            lines.Add(randVal + " = call i32 @rand()");
            lines.Add(diff + " = sub i32 " + highExpr + ", " + lowExpr);
            lines.Add(diff1 + " = add i32 " + diff + ", 1");
            lines.Add(modVal + " = srem i32 " + randVal + ", " + diff1);
            lines.Add(result + " = add i32 " + modVal + ", " + lowExpr);
            return result;
        }

        string GenerateTerm(Term term, List<string> lines, HashSet<string> locals)
        {
            var nodes = term.TermNodes;
            if (nodes.Count == 0)
            {
                string z = NewTemp();
                lines.Add(z + " = add i32 0, 0");
                return z;
            }

            string result = GenerateFactor(nodes[0].Factor, lines, locals);

            for (int i = 1; i < nodes.Count; i++)
            {
                string factorReg = GenerateFactor(nodes[i].Factor, lines, locals);
                string newResult = NewTemp();
                if (nodes[i].IsDivision)
                    lines.Add(newResult + " = sdiv i32 " + result + ", " + factorReg);
                else
                    lines.Add(newResult + " = mul i32 " + result + ", " + factorReg);
                result = newResult;
            }

            return result;
        }

        string GenerateFactor(Factor factor, List<string> lines, HashSet<string> locals)
        {
            if (factor is ConstantFactor cf)
            {
                string r = NewTemp();
                lines.Add(r + " = add i32 " + cf.Value + ", 0");
                return r;
            }
            else if (factor is IdentityFactor idf)
            {
                string val = NewTemp();
                lines.Add(val + " = load i32, i32* " + VarRef(idf.IdentityName, locals));
                return val;
            }
            else if (factor is ExpressionFactor ef)
            {
                string expr = GenerateExpression(ef.Expression, lines, locals);
                if (ef.Expression.ExpressionNodes.Count == 1 &&
                    ef.Expression.ExpressionNodes[0].IsPositive &&
                    ef.Expression.ExpressionNodes[0].Term.TermNodes.Count == 1)
                {
                    return expr;
                }
                string r = NewTemp();
                lines.Add(r + " = add i32 " + expr + ", 0");
                return r;
            }
            throw new Exception("Unknown factor type");
        }

        string GenerateCondition(Condition cond, List<string> lines, HashSet<string> locals)
        {
            if (cond is TrueCondition)
            {
                string r = NewTemp();
                lines.Add(r + " = add i32 1, 0");
                return r;
            }
            if (cond is FalseCondition)
            {
                string r = NewTemp();
                lines.Add(r + " = add i32 0, 0");
                return r;
            }
            if (cond is OddCondition odd)
            {
                string exprReg = GenerateExpression(odd.Expression, lines, locals);
                string andVal = NewTemp();
                string result = NewTemp();
                lines.Add(andVal + " = and i32 " + exprReg + ", 1");
                lines.Add(result + " = icmp ne i32 " + andVal + ", 0");
                return result;
            }
            var bin = (BinaryCondition)cond;
            string leftReg = GenerateExpression(bin.FirstExpression, lines, locals);
            string rightReg = GenerateExpression(bin.SecondExpression, lines, locals);
            string cmpReg = NewTemp();
            string cmpOp = bin.Type switch
            {
                ConditionType.Equal => "eq",
                ConditionType.NotEqual => "ne",
                ConditionType.LessThan => "slt",
                ConditionType.LessThanOrEqual => "sle",
                ConditionType.GreaterThan => "sgt",
                ConditionType.GreaterThanOrEqual => "sge",
                _ => throw new Exception("Unknown condition type")
            };
            lines.Add(cmpReg + " = icmp " + cmpOp + " i32 " + leftReg + ", " + rightReg);
            return cmpReg;
        }

        static string EscapeString(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
